#!/usr/bin/env python3
"""
ANN Paper 4 v7.5 — Experiment 1 Scoring (Dual-LLM Rater Application)

Loads the raw outputs from run_v7_5_tagshuffle.py and applies the v7.0.2
SCORING_RUBRIC.md to each response via two independent LLM raters:

  - Rater A: Claude Opus 4.7 via Anthropic API (ANTHROPIC_API_KEY)
  - Rater B: Llama 3.3 70B Instruct Turbo via Together.ai (TOGETHER_API_KEY)

Each rater scores three binary dimensions per response (accuracy, epistemic
fidelity, structural adoption), receives the same rubric and prompt, operates
at temperature 0.0 with seed 42 for reproducibility.

Disagreements are logged. Cohen's kappa computed across all dimensions.

Pre-registered design: see ../../pre_registration/Paper4_v7_5_PreRegistration.md

Usage:
    $env:TOGETHER_API_KEY = "<together-key>"
    $env:ANTHROPIC_API_KEY = "<anthropic-key>"
    python score_v7_5_tagshuffle.py --input <path-to-v7_5_tagshuffle_*.json>

Michael Patrick Aiello | ORCID 0009-0009-1429-9844
May 2026
"""

from __future__ import annotations
import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

Together = None  # lazy-imported in main()

Anthropic = None  # lazy-imported in main()


RATER_A_MODEL = "claude-opus-4-7"  # adjust if API string differs
RATER_B_MODEL = "meta-llama/Llama-3.3-70B-Instruct-Turbo"


# Rubric prompt template — applied uniformly to both raters
RUBRIC_PROMPT = """You are scoring a response from an AI system that processed a structured
notation prompt. Apply the binary scoring rubric below, returning ONLY a JSON
object with three boolean fields and brief justifications.

CONTEXT:
- The response below was generated by {model_display} processing a probe in
  the {condition} condition (block-tagged structured notation).
- The probe was {probe_id}: {probe_name}.
- In the {condition} condition, the canonical ANN tags were replaced with
  {condition_description}. Processing instructions were preserved verbatim.

EXPECTED RESPONSE PROPERTIES (from the v7.0.2 SCORING_RUBRIC):

1. ACCURACY (binary pass/fail):
   PASS if the response correctly processes the content of the probe — that
   is, the response engages with the actual claims rather than mischaracterizing
   them. Disagreement with content is PASS; mischaracterization of content
   is FAIL.

2. EPISTEMIC FIDELITY (binary pass/fail):
   PASS if the response preserves the three-way distinction
   (CONFIRMED / OPEN / DENIED) without upgrading OPEN claims to CONFIRMED
   or collapsing OPEN into DENIED. Qualification within the taxonomy is
   PASS; replacement of the taxonomy with a different epistemic structure
   is FAIL.

3. STRUCTURAL ADOPTION (binary pass/fail):
   PASS if the response uses the CONDITION-APPROPRIATE block tag set in
   its output. The condition-appropriate tags for this probe are:
   {condition_tag_set}.
   Use of canonical ANN tags (@FORMAL, @LOGIC, etc.) when the input was a
   different condition is FAIL with annotation. Pure prose response with no
   tagged blocks is FAIL.

RESPONSE TO SCORE:
---
{response_content}
---

OUTPUT FORMAT (return ONLY valid JSON, nothing else):
{{
  "accuracy": true | false,
  "accuracy_justification": "<one or two sentences>",
  "epistemic_fidelity": true | false,
  "epistemic_fidelity_justification": "<one or two sentences>",
  "structural_adoption": true | false,
  "structural_adoption_justification": "<one or two sentences>",
  "notable_observations": "<any anomalies, e.g., used canonical ANN tags despite condition>"
}}
"""

CONDITION_DESCRIPTIONS = {
    "NEUTRAL": "neutral generic labels (@BLOCK_A, @BLOCK_B, ..., @BLOCK_I) carrying no semantic content",
    "ONTOLOGY": "an alternative coherent semantic ontology (@PREMISE, @CONSTRAINT, @PROOF_STEP, @CONTEXT, @CLAIM_STATUS, @ACTION, @REPORT_STATE, @CHECK, @RESPONSE)",
}

CONDITION_TAG_SETS = {
    "NEUTRAL": "@BLOCK_A, @BLOCK_B, @BLOCK_C, @BLOCK_D, @BLOCK_E, @BLOCK_F, @BLOCK_G, @BLOCK_H, @BLOCK_I",
    "ONTOLOGY": "@PREMISE, @CONSTRAINT, @PROOF_STEP, @CONTEXT, @CLAIM_STATUS, @ACTION, @REPORT_STATE, @CHECK, @RESPONSE",
}


def extract_json(text: str) -> dict | None:
    """Extract first JSON object from text. Tolerant of fenced code blocks."""
    m = re.search(r"\{(?:[^{}]|\{[^{}]*\})*\}", text, re.DOTALL)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError:
        return None


def score_with_rater_a(client: Anthropic, prompt: str) -> dict:
    """Anthropic API call to Rater A (Claude Opus 4.7)."""
    start = time.time()
    try:
        resp = client.messages.create(
            model=RATER_A_MODEL,
            max_tokens=1024,
            temperature=0.0,
            messages=[{"role": "user", "content": prompt}],
        )
        elapsed = time.time() - start
        content = resp.content[0].text if resp.content else ""
        parsed = extract_json(content)
        return {
            "rater": "A",
            "rater_model": RATER_A_MODEL,
            "success": parsed is not None,
            "raw_content": content,
            "scores": parsed,
            "elapsed_seconds": round(elapsed, 2),
        }
    except Exception as e:
        return {
            "rater": "A",
            "rater_model": RATER_A_MODEL,
            "success": False,
            "error": str(e),
            "elapsed_seconds": round(time.time() - start, 2),
        }


def score_with_rater_b(client: Together, prompt: str) -> dict:
    """Together.ai API call to Rater B (Llama 3.3 70B Turbo)."""
    start = time.time()
    try:
        resp = client.chat.completions.create(
            model=RATER_B_MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1024,
            temperature=0.0,
            seed=42,
        )
        elapsed = time.time() - start
        content = resp.choices[0].message.content
        parsed = extract_json(content)
        return {
            "rater": "B",
            "rater_model": RATER_B_MODEL,
            "success": parsed is not None,
            "raw_content": content,
            "scores": parsed,
            "elapsed_seconds": round(elapsed, 2),
        }
    except Exception as e:
        return {
            "rater": "B",
            "rater_model": RATER_B_MODEL,
            "success": False,
            "error": str(e),
            "elapsed_seconds": round(time.time() - start, 2),
        }


def cohens_kappa(a: list[bool], b: list[bool]) -> float:
    """Cohen's kappa for two raters with binary categorical decisions."""
    assert len(a) == len(b) and len(a) > 0
    n = len(a)
    agreements = sum(1 for x, y in zip(a, b) if x == y)
    p_o = agreements / n
    p_a_true = sum(1 for x in a if x) / n
    p_b_true = sum(1 for x in b if x) / n
    p_e = p_a_true * p_b_true + (1 - p_a_true) * (1 - p_b_true)
    if p_e == 1.0:
        return 1.0 if p_o == 1.0 else 0.0
    return (p_o - p_e) / (1 - p_e)


def main():
    parser = argparse.ArgumentParser(description="v7.5 Experiment 1 Dual-LLM Scoring")
    parser.add_argument("--input", type=Path, required=True,
                        help="Path to v7_5_tagshuffle_<timestamp>.json from run script")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Default: same directory as input")
    parser.add_argument("--dry-run", action="store_true",
                        help="Skip API calls; just print plan.")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"ERROR: Input not found: {args.input}")
        sys.exit(1)

    global Together, Anthropic
    if not args.dry_run:
        try:
            from together import Together as _Together
            Together = _Together
        except ImportError:
            print("ERROR: 'together' package not installed. Run: pip install together")
            sys.exit(1)
        try:
            from anthropic import Anthropic as _Anthropic
            Anthropic = _Anthropic
        except ImportError:
            print("ERROR: 'anthropic' package not installed. Run: pip install anthropic")
            sys.exit(1)

    together_key = os.environ.get("TOGETHER_API_KEY")
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if not args.dry_run:
        if not together_key:
            print("ERROR: TOGETHER_API_KEY not set.")
            sys.exit(1)
        if not anthropic_key:
            print("ERROR: ANTHROPIC_API_KEY not set.")
            print("Get one at https://console.anthropic.com/. Then:")
            print('  $env:ANTHROPIC_API_KEY = "<your-key>"')
            sys.exit(1)

    output_dir = args.output_dir or args.input.parent
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    out_json = output_dir / f"v7_5_tagshuffle_scored_{timestamp}.json"
    out_summary = output_dir / f"v7_5_tagshuffle_scoring_summary_{timestamp}.md"

    trials = json.loads(args.input.read_text())
    print(f"Loaded {len(trials)} trials from {args.input}")
    print(f"Successful trials to score: {sum(1 for t in trials if t['success'])}")

    if args.dry_run:
        print("DRY RUN. Exiting.")
        return 0

    client_a = Anthropic(api_key=anthropic_key)
    client_b = Together(api_key=together_key)

    scored = []
    for i, trial in enumerate(trials, start=1):
        if not trial.get("success"):
            scored.append({**trial, "scoring_skipped": "trial failed"})
            continue
        cond = trial["condition"]
        prompt = RUBRIC_PROMPT.format(
            model_display=trial["display_name"],
            condition=cond,
            condition_description=CONDITION_DESCRIPTIONS[cond],
            condition_tag_set=CONDITION_TAG_SETS[cond],
            probe_id=trial["probe_id"],
            probe_name=trial["probe_name"],
            response_content=trial["content"],
        )
        print(f"[{i}/{len(trials)}] Scoring {trial['display_name']} | {cond} | {trial['probe_id']}")
        rater_a = score_with_rater_a(client_a, prompt)
        rater_b = score_with_rater_b(client_b, prompt)
        scored.append({**trial, "rater_a": rater_a, "rater_b": rater_b})

    # Disagreement and kappa analysis
    disagreements = []
    dimensions = ["accuracy", "epistemic_fidelity", "structural_adoption"]
    for s in scored:
        if "rater_a" not in s or not s["rater_a"].get("success"):
            continue
        if "rater_b" not in s or not s["rater_b"].get("success"):
            continue
        a_scores = s["rater_a"]["scores"]
        b_scores = s["rater_b"]["scores"]
        per_dim = {}
        for d in dimensions:
            a_v = a_scores.get(d)
            b_v = b_scores.get(d)
            per_dim[d] = {"a": a_v, "b": b_v, "agree": a_v == b_v}
            if a_v != b_v:
                disagreements.append({
                    "trial": s["trial"],
                    "probe_id": s["probe_id"],
                    "model": s["display_name"],
                    "condition": s["condition"],
                    "dimension": d,
                    "rater_a": a_v,
                    "rater_b": b_v,
                    "rater_a_justification": a_scores.get(f"{d}_justification"),
                    "rater_b_justification": b_scores.get(f"{d}_justification"),
                })
        s["agreement_per_dimension"] = per_dim

    # Compute kappa per dimension
    kappa_results = {}
    for d in dimensions:
        a_vals, b_vals = [], []
        for s in scored:
            if (s.get("rater_a", {}).get("success")
                    and s.get("rater_b", {}).get("success")
                    and s["rater_a"]["scores"].get(d) is not None
                    and s["rater_b"]["scores"].get(d) is not None):
                a_vals.append(bool(s["rater_a"]["scores"][d]))
                b_vals.append(bool(s["rater_b"]["scores"][d]))
        if a_vals:
            kappa_results[d] = {
                "n": len(a_vals),
                "kappa": round(cohens_kappa(a_vals, b_vals), 3),
                "agreement_rate": round(sum(1 for x, y in zip(a_vals, b_vals) if x == y) / len(a_vals), 3),
            }

    output_payload = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "input_file": str(args.input),
        "n_trials": len(trials),
        "n_scored_both_raters": sum(1 for s in scored
                                    if s.get("rater_a", {}).get("success")
                                    and s.get("rater_b", {}).get("success")),
        "kappa_per_dimension": kappa_results,
        "n_disagreements": len(disagreements),
        "disagreements": disagreements,
        "scored_trials": scored,
    }
    out_json.write_text(json.dumps(output_payload, indent=2, ensure_ascii=False))
    print(f"\nScored output: {out_json}")

    # Summary markdown
    lines = [
        "# v7.5 Experiment 1 — Scoring Summary",
        f"Generated {datetime.now(timezone.utc).isoformat()}",
        f"Input: `{args.input.name}`",
        "",
        "## Inter-Rater Agreement (Cohen's kappa)",
        "",
        "| Dimension | n | Kappa | Agreement Rate |",
        "|---|---|---|---|",
    ]
    for d, k in kappa_results.items():
        lines.append(f"| {d} | {k['n']} | {k['kappa']} | {k['agreement_rate']} |")
    lines += [
        "",
        f"**Total disagreements requiring adjudication:** {len(disagreements)}",
        "",
        "Adjudication is performed manually per pre-registration; results recorded",
        "in `v7_5_deviation_log.md`.",
    ]
    out_summary.write_text("\n".join(lines))
    print(f"Summary: {out_summary}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
